version: '3.9'
services:
    STSA-server:
        image: "kurobaneyui/stsa_flask_server:3.0"
        networks:
            - STSA-Network
        ports:
         - "6680:80"
        volumes:
         - "/home/ubuntu/all_websites/STSA:/home/STSA"
        tty: true
    
    STSA-Database:
        image: "mysql"
        networks:
            - STSA-Network
        ports:
         - "6606:3306"
        environment:
            MYSQL_ROOT_PASSWORD: "localtest"
    
networks:
    STSA-Network: