version: '3.3'
services:
    STSA-server:
        image: "kurobaneyui/stsa_flask_server:v3"
        ports:
         - "5580:80"
        volumes:
         - "/home/ubuntu/all_websites/STSA/website:/home/STSA"
        depends_on:
         - 'STSA-Database'
    
    STSA-Database:
        image: "mysql"
        ports:
         - "5506:3306"
         - "5560:33060"
        environment:
            MYSQL_ROOT_PASSWORD: "localtest"